// GENERATED FILE. Do not edit by hand.
//
// Generated by Tests/SidePulseCoreTests/LEDBuiltInProgramsSourceTests.swift from the
// Python project; regenerate with
//   SIDEPULSE_REGENERATE_BUILTINS=1 SIDEPULSE_PYTHON_REPO=<repo> \
//     swift test --filter LEDBuiltInProgramsSourceTests
// Sources:
//   src/sidepulse/resources/animations/*.LED  exact bytes minus the single trailing
//                                             newline; lid animations are excluded
//   src/sidepulse/settings.py                 catalog order (AGENT_ANIMATION_BUILT_INS)
//   src/sidepulse/status_bar.py               UI labels (agent_animation_label)
//   src/sidepulse/led_status.py               -2/-8 variants (COUNT_SPECIFIC_ANIMATIONS)
//   profiles/{cyan,ember,purple}.json         lid_open / lid_closed dropped

/// Embedded built-in animation data used by `AnimationLibrary` and
/// `AnimationProfiles`. No resource bundle is needed at runtime.
enum BuiltInPrograms {
    /// Built-in animations in catalog (UI) order.
    static let catalog: [Animation] = [
        Animation(id: "off", name: "Slow Off", countSpecific: false),
        Animation(id: "immediate-off", name: "Immediate Off", countSpecific: false),
        Animation(id: "idle-pulse", name: "Idle Pulse", countSpecific: true),
        Animation(id: "cyan-roll", name: "Cyan Roll", countSpecific: true),
        Animation(id: "cyan-complete", name: "Cyan Complete", countSpecific: false),
        Animation(id: "amber-pulse", name: "Amber Pulse", countSpecific: false),
        Animation(id: "solid-green", name: "Solid Green", countSpecific: false),
        Animation(id: "kitt", name: "KITT Scanner", countSpecific: true),
        Animation(id: "kitt-red", name: "KITT Scanner Red", countSpecific: true),
        Animation(id: "ember-idle", name: "Ember Idle", countSpecific: true),
        Animation(id: "ember-tide", name: "Ember Tide", countSpecific: true),
        Animation(id: "ember-attention", name: "Ember Attention", countSpecific: false),
        Animation(id: "ember-complete", name: "Ember Complete", countSpecific: false),
        Animation(id: "purple-idle", name: "Purple Idle", countSpecific: true),
        Animation(id: "purple-tide", name: "Purple Tide", countSpecific: true),
        Animation(id: "purple-attention", name: "Purple Attention", countSpecific: false),
        Animation(id: "purple-complete", name: "Purple Complete", countSpecific: false),
        Animation(id: "night-rider", name: "Night Rider", countSpecific: true),
    ]

    /// Program text keyed by file name: `<id>.LED`, or `<id>-2.LED` / `<id>-8.LED`
    /// for count-specific animations. Trailing newline stripped.
    static let files: [String: String] = [
        "amber-pulse.LED": #"""
            off
            #FF3A00 1.6s pulse
            repeat
            """#,
        "cyan-complete.LED": #"""
            #00E5FF 320ms cosine
            """#,
        "cyan-roll-2.LED": #"""
            off 320ms cosine
            0:#00E5FF 760ms pulse 0ms; 1:#00E5FF 760ms pulse 260ms
            repeat
            """#,
        "cyan-roll-8.LED": #"""
            off 320ms cosine
            0:#00E5FF 760ms pulse 0ms; 1:#00E5FF 760ms pulse 95ms; 2:#00E5FF 760ms pulse 190ms; 3:#00E5FF 760ms pulse 285ms; 4:#00E5FF 760ms pulse 380ms; 5:#00E5FF 760ms pulse 475ms; 6:#00E5FF 760ms pulse 570ms; 7:#00E5FF 760ms pulse 665ms
            repeat
            """#,
        "ember-attention.LED": #"""
            off
            #F23819 1.6s pulse
            repeat
            """#,
        "ember-complete.LED": #"""
            #F23819 320ms cosine
            """#,
        "ember-idle-2.LED": #"""
            off 2s
            0:#F23819 1:#F23819 2s ease
            repeat
            """#,
        "ember-idle-8.LED": #"""
            off 2s
            2:#972310 3:#F23819 4:#F23819 5:#972310 2s ease
            repeat
            """#,
        "ember-tide-2.LED": #"""
            off 320ms cosine
            0:#F23819 760ms pulse 0ms; 1:#F23819 760ms pulse 260ms
            repeat
            """#,
        "ember-tide-8.LED": #"""
            off 320ms cosine
            0:#F23819 760ms pulse 0ms; 1:#F23819 760ms pulse 95ms; 2:#F23819 760ms pulse 190ms; 3:#F23819 760ms pulse 285ms; 4:#F23819 760ms pulse 380ms; 5:#F23819 760ms pulse 475ms; 6:#F23819 760ms pulse 570ms; 7:#F23819 760ms pulse 665ms
            repeat
            """#,
        "idle-pulse-2.LED": #"""
            off 2s
            0:#006060 1:#006060 2s ease
            repeat
            """#,
        "idle-pulse-8.LED": #"""
            off 2s
            2:#006060 3:#00E5FF 4:#00E5FF 5:#006060 2s ease
            repeat
            """#,
        "immediate-off.LED": #"""
            off
            """#,
        "kitt-2.LED": #"""
            off 80ms cosine
            0:#00E5FF 320ms pulse 0ms; 1:#00E5FF 320ms pulse 240ms
            0:#00E5FF 320ms pulse 0ms
            repeat
            """#,
        "kitt-8.LED": #"""
            off 80ms cosine
            0:#00E5FF 320ms pulse 0ms; 1:#00E5FF 320ms pulse 85ms; 2:#00E5FF 320ms pulse 170ms; 3:#00E5FF 320ms pulse 255ms; 4:#00E5FF 320ms pulse 340ms; 5:#00E5FF 320ms pulse 425ms; 6:#00E5FF 320ms pulse 510ms; 7:#00E5FF 320ms pulse 595ms
            6:#00E5FF 320ms pulse 0ms; 5:#00E5FF 320ms pulse 85ms; 4:#00E5FF 320ms pulse 170ms; 3:#00E5FF 320ms pulse 255ms; 2:#00E5FF 320ms pulse 340ms; 1:#00E5FF 320ms pulse 425ms; 0:#00E5FF 320ms pulse 510ms
            repeat
            """#,
        "kitt-red-2.LED": #"""
            off 80ms cosine
            0:#FF1800 320ms pulse 0ms; 1:#FF1800 320ms pulse 240ms
            0:#FF1800 320ms pulse 0ms
            repeat
            """#,
        "kitt-red-8.LED": #"""
            off 80ms cosine
            0:#FF1800 320ms pulse 0ms; 1:#FF1800 320ms pulse 85ms; 2:#FF1800 320ms pulse 170ms; 3:#FF1800 320ms pulse 255ms; 4:#FF1800 320ms pulse 340ms; 5:#FF1800 320ms pulse 425ms; 6:#FF1800 320ms pulse 510ms; 7:#FF1800 320ms pulse 595ms
            6:#FF1800 320ms pulse 0ms; 5:#FF1800 320ms pulse 85ms; 4:#FF1800 320ms pulse 170ms; 3:#FF1800 320ms pulse 255ms; 2:#FF1800 320ms pulse 340ms; 1:#FF1800 320ms pulse 425ms; 0:#FF1800 320ms pulse 510ms
            repeat
            """#,
        "night-rider-2.LED": #"""
            off
            0:#FF1200 360ms pulse;1:#FF1200 360ms pulse 90ms
            repeat
            """#,
        "night-rider-8.LED": #"""
            off
            0:#FF1200 360ms pulse;1:#FF1200 360ms pulse 90ms;2:#FF1200 360ms pulse 180ms;3:#FF1200 360ms pulse 270ms;4:#FF1200 360ms pulse 360ms;5:#FF1200 360ms pulse 450ms;6:#FF1200 360ms pulse 540ms;7:#FF1200 360ms pulse 630ms
            6:#FF1200 360ms pulse;5:#FF1200 360ms pulse 90ms;4:#FF1200 360ms pulse 180ms;3:#FF1200 360ms pulse 270ms;2:#FF1200 360ms pulse 360ms;1:#FF1200 360ms pulse 450ms
            repeat
            """#,
        "off.LED": #"""
            off 1s
            """#,
        "purple-attention.LED": #"""
            off
            #FF00FF 1.6s pulse
            repeat
            """#,
        "purple-complete.LED": #"""
            #FF00FF 320ms cosine
            """#,
        "purple-idle-2.LED": #"""
            off 2s
            0:#FF00FF 1:#FF00FF 2s ease
            repeat
            """#,
        "purple-idle-8.LED": #"""
            off 2s
            2:#9F009F 3:#FF00FF 4:#FF00FF 5:#9F009F 2s ease
            repeat
            """#,
        "purple-tide-2.LED": #"""
            off 320ms cosine
            0:#FF00FF 760ms pulse 0ms; 1:#FF00FF 760ms pulse 260ms
            repeat
            """#,
        "purple-tide-8.LED": #"""
            off 320ms cosine
            0:#FF00FF 760ms pulse 0ms; 1:#FF00FF 760ms pulse 95ms; 2:#FF00FF 760ms pulse 190ms; 3:#FF00FF 760ms pulse 285ms; 4:#FF00FF 760ms pulse 380ms; 5:#FF00FF 760ms pulse 475ms; 6:#FF00FF 760ms pulse 570ms; 7:#FF00FF 760ms pulse 665ms
            repeat
            """#,
        "solid-green.LED": #"""
            #00FF66 320ms cosine
            """#,
    ]

    /// Built-in profiles in menu order (Cyan = the defaults).
    static let profiles: [AnimationProfile] = [
        AnimationProfile(id: "profile:cyan", name: "Cyan", animations: [
            .idleReady: "idle-pulse",
            .working: "cyan-roll",
            .toolRunning: "cyan-roll",
            .waitingForInput: "amber-pulse",
            .longTaskProgress: "cyan-roll",
            .blockedError: "amber-pulse",
            .completed: "cyan-complete",
            .unknown: "idle-pulse",
        ]),
        AnimationProfile(id: "profile:ember", name: "Ember", animations: [
            .idleReady: "ember-idle",
            .working: "ember-tide",
            .toolRunning: "ember-tide",
            .waitingForInput: "ember-attention",
            .longTaskProgress: "ember-tide",
            .blockedError: "ember-attention",
            .completed: "ember-complete",
            .unknown: "ember-idle",
        ]),
        AnimationProfile(id: "profile:purple", name: "Purple", animations: [
            .idleReady: "purple-idle",
            .working: "purple-tide",
            .toolRunning: "purple-tide",
            .waitingForInput: "purple-attention",
            .longTaskProgress: "purple-tide",
            .blockedError: "purple-attention",
            .completed: "purple-complete",
            .unknown: "purple-idle",
        ]),
    ]
}
